### ISSUE TITLE
Add description field and appointment type coding input param

### ISSUE THREAD

**Issue by haleyjohnso** [canvas-medical/embed#113]
## Context

Discussed in [status ](https://www.notion.so/vigetlabs/Status-Report-Week-6-1d24f03d54f34203a81bdf2aa77621f9)

## Description 

Background:There are two ways that a practice can configure why a patient is there — either a numerical code, or a free text description. Numerical code is preconfigured in environment. Description comes in a a comment.
- [ ]  Add description field and appointment type coding input param 
    - Appointment type coding as an object with system coding display
    - Appointment description which gets mapped to the appointment field

**Comment by ReyBernDia** [comment]
these fields have been added
